sudo: false
dist: trusty
language: node_js
node_js:
- '9'
install:
- npm install
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
script: 
- npm run build
# cache node_modules to speed up build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
cache:
  directories:
    - node_modules
