sudo: false
dist: trusty
language: node_js
node_js:
    - "8"

before_script:
    - git config --global user.email "travis@travis-ci.org"
    - git config --global user.name "Travis CI"
script:
    - cd ./travis
    - sh travis.sh
deploy:
    provider: pages
    target_branch: travis
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: ../
    on:
        branch: travis-two
