sass:
    sass_dir: assets/css

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  documentation:
    output: true
    permalink: /docs/:path

exclude:
  - .DS_Store
  - Gemfile.lock
  - node_modules
  - images/original
  - images/scripts
